export const PATH = {
  home: "/",
  userInfo: "/userInfo",
  draft: "/draft",
  login: "/login",
  resetPassword: "/reset-password",
  createRequest: "/createClaim",
  pending: "/pending",
  details: "/details/:id",
  myClaims: "/myClaims",
  userClaimDetails: "/userClaim/:id",
  userSettings: "/userSettings",
  approveDetails: "/approveDetails",
  claimStatus: "/claimStatus",
  paidClaim: "/paidClaim",
  approved: "/approved",
};
